---
title: "First Knit"
author: "Xin"
date: "September, 2019"
output: 
  html_document:
    number_sections: true
    toc: true
---

### `r as.character(Sys.Date())`


# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. Half the points in this assignment depend on your picture and name being correct!!  Be sure to put your photo in the AAA_Owner_Info folder and call it My_photo.jpg after first renaming the current one to Koala.jpg . 

##Where are you now?  
What row are you in, front,middle or back?  Do you usually choose a similiar row in other classes? What is the computer number where you are sitting?  How on a scale of 1 to 10 (1=low, 10=high) How you feel about periodic seat re-assignment, say how and why. Teams, have you ever worked on one in a class setting?  

###my answer     
  
   
 I joined the class for first time,so i just didn't know that i should take a 
 computer.I am sorry for that.I was the guy who changed his seat from the 3rd
 row to 1st row in order to see slides clearly.
 Yes in case I need to charge my phone or computer. 
 There is no computer number here. 
 7. because i want to feel some unsimilar experiences.
 No,i am a Chinese,so it's very different from USA and i haven't ever work in that pattern before.
 
 


##Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want me to call you something else - what would that be? 

###my answer     
  
   Xin or Sheen is Okay.
 




##Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

###my answer     
  
   To be a great great data scientist.Maybe math ,but i am not that sure.I have no idea about that.



##Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

###my answer     
  
   
  USA is the first foreign country i have ever been,and it's the only foreign 
  country .I am not sure about the second question.




##Why are you taking Math 115?  
What grade do you need to attain in stats to not upset your future plans, What is your plan?
 

###my answer     
  
   My major is statistics in China,higher the better.
 





##Homework Help and Getting around?  
On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  Do you have a computer you can use at home? If so, what kind is it (windows, Apple, Linux)? Do you have internet access at home?  
How do you get to class? Are there issues that limit when you can be at the college?Where and when did you attend high school?  Do you currently have a job?

###my answer   
  
   
  3.Yes,i have a computer.Windows.Yes.I go to class by walking.No.eight years ago.
  No,i dont have a job.




